package dashboard

const pageTemplate = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Activity Tracker</title><style>
:root{--bg:#0b0d10;--card:#12161c;--muted:#8590a2;--line:#232a35;--text:#e7edf5;--accent:#7dd3fc;--good:#86efac;--warn:#fbbf24}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px ui-sans-serif,system-ui,-apple-system,sans-serif}.wrap{max-width:1380px;margin:auto;padding:28px}h1{font-size:28px;margin:0}.sub{color:var(--muted);margin:6px 0 22px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 20px}.toolbar a{color:var(--text);text-decoration:none;border:1px solid var(--line);padding:8px 11px;border-radius:8px}.toolbar a.on{border-color:var(--accent);color:var(--accent)}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:15px}.metric .v{font-size:24px;font-weight:700}.metric .k{color:var(--muted);margin-top:5px}.section{margin-top:22px}.section h2{font-size:16px;margin:0 0 10px}.split{display:grid;grid-template-columns:1.2fr 1fr;gap:12px}.barrow{display:grid;grid-template-columns:minmax(110px,2fr) 5fr 70px;gap:10px;align-items:center;margin:8px 0}.bar{height:8px;background:#202731;border-radius:20px;overflow:hidden}.fill{height:100%;background:var(--accent);border-radius:20px}.name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.muted{color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px 8px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-weight:500}.insight{border-left:3px solid var(--accent);padding:10px 12px;margin:8px 0;background:#10151b}.insight.warning{border-color:var(--warn)}.insight.good{border-color:var(--good)}.hours{display:grid;grid-template-columns:repeat(24,1fr);gap:3px;height:100px;align-items:end}.h{background:var(--accent);min-height:2px;opacity:.85}.hourlabels{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;margin-top:4px}.score{font-size:42px;font-weight:800}.tiny{font-size:12px;color:var(--muted)}@media(max-width:1000px){.grid{grid-template-columns:repeat(3,1fr)}.split{grid-template-columns:1fr}}@media(max-width:600px){.wrap{padding:15px}.grid{grid-template-columns:repeat(2,1fr)}}
</style></head><body><div class="wrap"><h1>Activity Tracker</h1><div class="sub">Local-only Hyprland attention analytics · last {{.Days}} day(s)</div><div class="toolbar"><a class="{{if eq .Days 1}}on{{end}}" href="/?days=1">1d</a><a class="{{if eq .Days 3}}on{{end}}" href="/?days=3">3d</a><a class="{{if eq .Days 7}}on{{end}}" href="/?days=7">7d</a><a class="{{if eq .Days 14}}on{{end}}" href="/?days=14">14d</a><a class="{{if eq .Days 30}}on{{end}}" href="/?days=30">30d</a><a href="/export.csv?days={{.Days}}">Export CSV</a></div>
<div class="grid"><div class="card metric"><div class="v">{{printf "%.1fh" .Summary.TrackedHours}}</div><div class="k">Tracked time</div></div><div class="card metric"><div class="v">{{printf "%.0f" .Summary.FocusScore}}</div><div class="k">Focus score /100</div></div><div class="card metric"><div class="v">{{printf "%.1fh" .Summary.DeepWorkHours}}</div><div class="k">25m+ focus</div></div><div class="card metric"><div class="v">{{printf "%.1f" .Summary.SwitchesPerHour}}</div><div class="k">Switches / hour</div></div><div class="card metric"><div class="v">{{printf "%.1fm" .Summary.MedianFocusMinutes}}</div><div class="k">Median focus span</div></div><div class="card metric"><div class="v">{{printf "%.0f%%" .Summary.BounceRate}}</div><div class="k">Bounce-back rate</div></div></div>
<div class="section split"><div class="card"><h2>Attention diagnosis</h2>{{if .Summary.Insights}}{{range .Summary.Insights}}<div class="insight {{.Level}}"><b>{{.Title}}</b><div class="muted">{{.Text}}</div></div>{{end}}{{else}}<div class="muted">Not enough data yet.</div>{{end}}</div><div class="card"><h2>Focus profile</h2><div class="score">{{printf "%.0f" .Summary.FocusScore}}</div><table><tr><td>Fragmentation</td><td>{{printf "%.0f/100" .Summary.FragmentationScore}}</td></tr><tr><td>Deep-work share</td><td>{{printf "%.0f%%" .Summary.DeepWorkRatio}}</td></tr><tr><td>Longest focus run</td><td>{{printf "%.0fm" .Summary.LongestFocusMinutes}}</td></tr><tr><td>Flow blocks</td><td>{{.Summary.FlowBlocks}}</td></tr><tr><td>App entropy</td><td>{{printf "%.2f" .Summary.AppEntropy}}</td></tr><tr><td>Routine consistency</td><td>{{printf "%.0f/100" .Summary.RoutineConsistency}}</td></tr><tr><td>Peak activity hour</td><td>{{hour .Summary.PeakHour}}</td></tr></table></div></div>
<div class="section split"><div class="card"><h2>Top applications</h2>{{range .Summary.Apps}}<div class="barrow"><div class="name" title="{{.Name}}">{{.Name}}</div><div class="bar"><div class="fill" style="width:{{printf "%.1f" .Percent}}%"></div></div><div class="muted">{{dur .Seconds}}</div></div>{{end}}</div><div class="card"><h2>Workspaces</h2>{{range .Summary.Workspaces}}<div class="barrow"><div class="name">{{.Name}}</div><div class="bar"><div class="fill" style="width:{{printf "%.1f" .Percent}}%"></div></div><div class="muted">{{dur .Seconds}}</div></div>{{end}}</div></div>
<div class="section card"><h2>Hourly distribution</h2><div class="hours">{{range .Summary.Hours}}<div class="h" title="{{printf "%02d:00" .Hour}} · {{dur .Seconds}} · {{.Switches}} switches" style="height:{{if gt .Seconds 0.0}}{{printf "%.0f" (hourHeight .Seconds $.Summary.Hours)}}{{else}}2{{end}}%"></div>{{end}}</div><div class="hourlabels"><span>00</span><span>06</span><span>12</span><span>18</span><span>23</span></div></div>
<div class="section card"><h2>Daily breakdown</h2><table><thead><tr><th>Date</th><th>Tracked</th><th>Deep</th><th>Switches</th><th>First</th><th>Last</th></tr></thead><tbody>{{range .Summary.Days}}<tr><td>{{.Date}}</td><td>{{printf "%.1fh" .Hours}}</td><td>{{printf "%.1fh" .DeepHours}}</td><td>{{.Switches}}</td><td>{{.First}}</td><td>{{.Last}}</td></tr>{{end}}</tbody></table></div>
<div class="section card"><h2>Top window contexts</h2><div class="tiny">Window titles stay on this machine. They are useful for separating tabs/projects inside the same application.</div><table>{{range .Summary.Contexts}}<tr><td class="name" title="{{.Name}}">{{.Name}}</td><td>{{dur .Seconds}}</td><td>{{printf "%.1f%%" .Percent}}</td></tr>{{end}}</table></div>
<div class="section card"><h2>Recent raw timeline</h2><table><thead><tr><th>Start</th><th>Duration</th><th>App</th><th>Workspace</th><th>Title</th></tr></thead><tbody>{{range $r := .Recent}}{{with $r.Window}}<tr><td>{{$r.Start.Format "2006-01-02 15:04:05"}}</td><td>{{msdur $r.DurationMS}}</td><td>{{.Class}}</td><td>{{.Workspace.Name}}</td><td class="name" title="{{.Title}}">{{.Title}}</td></tr>{{end}}{{end}}</tbody></table><div class="tiny">For exact raw data use Export CSV.</div></div>
</div></body></html>`
